
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: Custom
    file_sd_configs:
      - files:
          - /service-discovery/targets.json
        refresh_interval: 10s

